Lint/NotNil:
  Excluded:
  - benchmark/benchmark.cr
  Enabled: true

Naming/BlockParameterName:
  AllowNamesEndingInNumbers: true
  Enabled: false

Lint/DebugCalls:
  Excluded:
  - samples/*
  Enabled: true
